name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node.js 20 setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install node dependencies
        run: npm ci

      - name: Go 1.24.1 setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Install go dependencies
        run: go mod download

      - name: Node lint
        run: npm run lint

      - name: Tailwind build
        run: npx tailwindcss -i ./frontend/src/assets/input.css -o ./frontend/src/assets/output.css --minify

      - name: Node build
        run: npm run build

      - name: Node test
        run: npm run test

      - name: Email build
        run: npx email export --dir "backend/emails/templates" --outDir "backend/out" --pretty

      - name: Go build
        run: go build -o backend/bin/reservations backend/cmd/main.go

      - name: Go lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2

      - name: Go test
        run: go test ./backend/...
