name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node.js 20 setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install node dependencies
        run: npm ci

      - name: Go 1.25.1 setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Install go dependencies
        run: go mod download

      - name: Node lint
        run: npm run lint

      - name: Jabulani tailwind build
        run: npx @tailwindcss/cli -i ./frontend/apps/jabulani/input.css -o ./frontend/apps/jabulani/src/output.css --minify

      - name: Jabulani node build
        run: npm run build-jabulani

      - name: Tango tailwind build
        run: npx @tailwindcss/cli -i ./frontend/apps/tango/input.css -o ./frontend/apps/tango/src/output.css --minify

      - name: Tango node build
        run: npm run build-tango

      - name: Node test
        run: npm run test

      - name: Email build
        run: npx email export --dir "backend/emails/templates" --outDir "backend/emails/out" --pretty

      - name: Go build
        run: go build -tags=prod -o backend/bin/reservations backend/cmd/main.go

      - name: Go lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2

      - name: Go test
        run: go test -v ./backend/...
